/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupInternalX7k2RouteImport } from './routes/signup-internal-x7k2'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitesRouteImport } from './routes/opportunites'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuichetRouteImport } from './routes/guichet'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReclamationsIndexRouteImport } from './routes/reclamations.index'
import { Route as ProspectsIndexRouteImport } from './routes/prospects.index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as UsersUsernameRouteImport } from './routes/users.$username'
import { Route as ReclamationsIdRouteImport } from './routes/reclamations.$id'
import { Route as ProspectsNewRouteImport } from './routes/prospects.new'
import { Route as ProspectsProspectIdRouteImport } from './routes/prospects.$prospectId'
import { Route as OpportunitiesOpportunityIdRouteImport } from './routes/opportunities.$opportunityId'
import { Route as JourneyProspectIdRouteImport } from './routes/journey.$prospectId'
import { Route as HrPayrollRouteImport } from './routes/hr.payroll'
import { Route as HrExternalAgentsRouteImport } from './routes/hr.external-agents'
import { Route as HrCommissionsRouteImport } from './routes/hr.commissions'
import { Route as HrAttendanceRouteImport } from './routes/hr.attendance'
import { Route as GuichetAnalyticsRouteImport } from './routes/guichet_.analytics'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'
import { Route as CalendarDateRouteImport } from './routes/calendar.$date'
import { Route as ProspectsProspectIdEditRouteImport } from './routes/prospects.$prospectId_.edit'
import { Route as OpportunitiesOpportunityIdEditRouteImport } from './routes/opportunities.$opportunityId_.edit'
import { Route as ContractsContractIdEditRouteImport } from './routes/contracts.$contractId_.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupInternalX7k2Route = SignupInternalX7k2RouteImport.update({
  id: '/signup-internal-x7k2',
  path: '/signup-internal-x7k2',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitesRoute = OpportunitesRouteImport.update({
  id: '/opportunites',
  path: '/opportunites',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuichetRoute = GuichetRouteImport.update({
  id: '/guichet',
  path: '/guichet',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamationsIndexRoute = ReclamationsIndexRouteImport.update({
  id: '/reclamations/',
  path: '/reclamations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsIndexRoute = ProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRoute = UsersUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => UsersRoute,
} as any)
const ReclamationsIdRoute = ReclamationsIdRouteImport.update({
  id: '/reclamations/$id',
  path: '/reclamations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsNewRoute = ProspectsNewRouteImport.update({
  id: '/prospects/new',
  path: '/prospects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsProspectIdRoute = ProspectsProspectIdRouteImport.update({
  id: '/prospects/$prospectId',
  path: '/prospects/$prospectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdRoute =
  OpportunitiesOpportunityIdRouteImport.update({
    id: '/opportunities/$opportunityId',
    path: '/opportunities/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const JourneyProspectIdRoute = JourneyProspectIdRouteImport.update({
  id: '/journey/$prospectId',
  path: '/journey/$prospectId',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrExternalAgentsRoute = HrExternalAgentsRouteImport.update({
  id: '/hr/external-agents',
  path: '/hr/external-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const HrCommissionsRoute = HrCommissionsRouteImport.update({
  id: '/hr/commissions',
  path: '/hr/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuichetAnalyticsRoute = GuichetAnalyticsRouteImport.update({
  id: '/guichet_/analytics',
  path: '/guichet/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDateRoute = CalendarDateRouteImport.update({
  id: '/calendar/$date',
  path: '/calendar/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsProspectIdEditRoute = ProspectsProspectIdEditRouteImport.update({
  id: '/prospects/$prospectId_/edit',
  path: '/prospects/$prospectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesOpportunityIdEditRoute =
  OpportunitiesOpportunityIdEditRouteImport.update({
    id: '/opportunities/$opportunityId_/edit',
    path: '/opportunities/$opportunityId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractsContractIdEditRoute = ContractsContractIdEditRouteImport.update({
  id: '/contracts/$contractId_/edit',
  path: '/contracts/$contractId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/backoffice': typeof BackofficeRoute
  '/configuration': typeof ConfigurationRoute
  '/dispatch': typeof DispatchRoute
  '/documentation': typeof DocumentationRoute
  '/guichet': typeof GuichetRoute
  '/login': typeof LoginRoute
  '/messaging': typeof MessagingRoute
  '/notifications': typeof NotificationsRoute
  '/objectives': typeof ObjectivesRoute
  '/opportunites': typeof OpportunitesRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/signup-internal-x7k2': typeof SignupInternalX7k2Route
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRouteWithChildren
  '/calendar/$date': typeof CalendarDateRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/guichet/analytics': typeof GuichetAnalyticsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/commissions': typeof HrCommissionsRoute
  '/hr/external-agents': typeof HrExternalAgentsRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/journey/$prospectId': typeof JourneyProspectIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/prospects/$prospectId': typeof ProspectsProspectIdRoute
  '/prospects/new': typeof ProspectsNewRoute
  '/reclamations/$id': typeof ReclamationsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/calendar/': typeof CalendarIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
  '/reclamations/': typeof ReclamationsIndexRoute
  '/contracts/$contractId/edit': typeof ContractsContractIdEditRoute
  '/opportunities/$opportunityId/edit': typeof OpportunitiesOpportunityIdEditRoute
  '/prospects/$prospectId/edit': typeof ProspectsProspectIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/backoffice': typeof BackofficeRoute
  '/configuration': typeof ConfigurationRoute
  '/dispatch': typeof DispatchRoute
  '/documentation': typeof DocumentationRoute
  '/guichet': typeof GuichetRoute
  '/login': typeof LoginRoute
  '/messaging': typeof MessagingRoute
  '/notifications': typeof NotificationsRoute
  '/objectives': typeof ObjectivesRoute
  '/opportunites': typeof OpportunitesRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/signup-internal-x7k2': typeof SignupInternalX7k2Route
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRouteWithChildren
  '/calendar/$date': typeof CalendarDateRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/guichet/analytics': typeof GuichetAnalyticsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/commissions': typeof HrCommissionsRoute
  '/hr/external-agents': typeof HrExternalAgentsRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/journey/$prospectId': typeof JourneyProspectIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/prospects/$prospectId': typeof ProspectsProspectIdRoute
  '/prospects/new': typeof ProspectsNewRoute
  '/reclamations/$id': typeof ReclamationsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/calendar': typeof CalendarIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/prospects': typeof ProspectsIndexRoute
  '/reclamations': typeof ReclamationsIndexRoute
  '/contracts/$contractId/edit': typeof ContractsContractIdEditRoute
  '/opportunities/$opportunityId/edit': typeof OpportunitiesOpportunityIdEditRoute
  '/prospects/$prospectId/edit': typeof ProspectsProspectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/backoffice': typeof BackofficeRoute
  '/configuration': typeof ConfigurationRoute
  '/dispatch': typeof DispatchRoute
  '/documentation': typeof DocumentationRoute
  '/guichet': typeof GuichetRoute
  '/login': typeof LoginRoute
  '/messaging': typeof MessagingRoute
  '/notifications': typeof NotificationsRoute
  '/objectives': typeof ObjectivesRoute
  '/opportunites': typeof OpportunitesRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/security': typeof SecurityRoute
  '/signup-internal-x7k2': typeof SignupInternalX7k2Route
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRouteWithChildren
  '/calendar/$date': typeof CalendarDateRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/guichet_/analytics': typeof GuichetAnalyticsRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/commissions': typeof HrCommissionsRoute
  '/hr/external-agents': typeof HrExternalAgentsRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/journey/$prospectId': typeof JourneyProspectIdRoute
  '/opportunities/$opportunityId': typeof OpportunitiesOpportunityIdRoute
  '/prospects/$prospectId': typeof ProspectsProspectIdRoute
  '/prospects/new': typeof ProspectsNewRoute
  '/reclamations/$id': typeof ReclamationsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/calendar/': typeof CalendarIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/prospects/': typeof ProspectsIndexRoute
  '/reclamations/': typeof ReclamationsIndexRoute
  '/contracts/$contractId_/edit': typeof ContractsContractIdEditRoute
  '/opportunities/$opportunityId_/edit': typeof OpportunitiesOpportunityIdEditRoute
  '/prospects/$prospectId_/edit': typeof ProspectsProspectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/backoffice'
    | '/configuration'
    | '/dispatch'
    | '/documentation'
    | '/guichet'
    | '/login'
    | '/messaging'
    | '/notifications'
    | '/objectives'
    | '/opportunites'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/roles'
    | '/security'
    | '/signup-internal-x7k2'
    | '/tasks'
    | '/users'
    | '/calendar/$date'
    | '/contracts/$contractId'
    | '/guichet/analytics'
    | '/hr/attendance'
    | '/hr/commissions'
    | '/hr/external-agents'
    | '/hr/payroll'
    | '/journey/$prospectId'
    | '/opportunities/$opportunityId'
    | '/prospects/$prospectId'
    | '/prospects/new'
    | '/reclamations/$id'
    | '/users/$username'
    | '/calendar/'
    | '/contracts/'
    | '/opportunities/'
    | '/prospects/'
    | '/reclamations/'
    | '/contracts/$contractId/edit'
    | '/opportunities/$opportunityId/edit'
    | '/prospects/$prospectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/backoffice'
    | '/configuration'
    | '/dispatch'
    | '/documentation'
    | '/guichet'
    | '/login'
    | '/messaging'
    | '/notifications'
    | '/objectives'
    | '/opportunites'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/roles'
    | '/security'
    | '/signup-internal-x7k2'
    | '/tasks'
    | '/users'
    | '/calendar/$date'
    | '/contracts/$contractId'
    | '/guichet/analytics'
    | '/hr/attendance'
    | '/hr/commissions'
    | '/hr/external-agents'
    | '/hr/payroll'
    | '/journey/$prospectId'
    | '/opportunities/$opportunityId'
    | '/prospects/$prospectId'
    | '/prospects/new'
    | '/reclamations/$id'
    | '/users/$username'
    | '/calendar'
    | '/contracts'
    | '/opportunities'
    | '/prospects'
    | '/reclamations'
    | '/contracts/$contractId/edit'
    | '/opportunities/$opportunityId/edit'
    | '/prospects/$prospectId/edit'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/backoffice'
    | '/configuration'
    | '/dispatch'
    | '/documentation'
    | '/guichet'
    | '/login'
    | '/messaging'
    | '/notifications'
    | '/objectives'
    | '/opportunites'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/roles'
    | '/security'
    | '/signup-internal-x7k2'
    | '/tasks'
    | '/users'
    | '/calendar/$date'
    | '/contracts/$contractId'
    | '/guichet_/analytics'
    | '/hr/attendance'
    | '/hr/commissions'
    | '/hr/external-agents'
    | '/hr/payroll'
    | '/journey/$prospectId'
    | '/opportunities/$opportunityId'
    | '/prospects/$prospectId'
    | '/prospects/new'
    | '/reclamations/$id'
    | '/users/$username'
    | '/calendar/'
    | '/contracts/'
    | '/opportunities/'
    | '/prospects/'
    | '/reclamations/'
    | '/contracts/$contractId_/edit'
    | '/opportunities/$opportunityId_/edit'
    | '/prospects/$prospectId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BackofficeRoute: typeof BackofficeRoute
  ConfigurationRoute: typeof ConfigurationRoute
  DispatchRoute: typeof DispatchRoute
  DocumentationRoute: typeof DocumentationRoute
  GuichetRoute: typeof GuichetRoute
  LoginRoute: typeof LoginRoute
  MessagingRoute: typeof MessagingRoute
  NotificationsRoute: typeof NotificationsRoute
  ObjectivesRoute: typeof ObjectivesRoute
  OpportunitesRoute: typeof OpportunitesRoute
  ProfileRoute: typeof ProfileRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SecurityRoute: typeof SecurityRoute
  SignupInternalX7k2Route: typeof SignupInternalX7k2Route
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRouteWithChildren
  CalendarDateRoute: typeof CalendarDateRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  GuichetAnalyticsRoute: typeof GuichetAnalyticsRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrCommissionsRoute: typeof HrCommissionsRoute
  HrExternalAgentsRoute: typeof HrExternalAgentsRoute
  HrPayrollRoute: typeof HrPayrollRoute
  JourneyProspectIdRoute: typeof JourneyProspectIdRoute
  OpportunitiesOpportunityIdRoute: typeof OpportunitiesOpportunityIdRoute
  ProspectsProspectIdRoute: typeof ProspectsProspectIdRoute
  ProspectsNewRoute: typeof ProspectsNewRoute
  ReclamationsIdRoute: typeof ReclamationsIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ProspectsIndexRoute: typeof ProspectsIndexRoute
  ReclamationsIndexRoute: typeof ReclamationsIndexRoute
  ContractsContractIdEditRoute: typeof ContractsContractIdEditRoute
  OpportunitiesOpportunityIdEditRoute: typeof OpportunitiesOpportunityIdEditRoute
  ProspectsProspectIdEditRoute: typeof ProspectsProspectIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-internal-x7k2': {
      id: '/signup-internal-x7k2'
      path: '/signup-internal-x7k2'
      fullPath: '/signup-internal-x7k2'
      preLoaderRoute: typeof SignupInternalX7k2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunites': {
      id: '/opportunites'
      path: '/opportunites'
      fullPath: '/opportunites'
      preLoaderRoute: typeof OpportunitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guichet': {
      id: '/guichet'
      path: '/guichet'
      fullPath: '/guichet'
      preLoaderRoute: typeof GuichetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamations/': {
      id: '/reclamations/'
      path: '/reclamations'
      fullPath: '/reclamations/'
      preLoaderRoute: typeof ReclamationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/': {
      id: '/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof ProspectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username': {
      id: '/users/$username'
      path: '/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameRouteImport
      parentRoute: typeof UsersRoute
    }
    '/reclamations/$id': {
      id: '/reclamations/$id'
      path: '/reclamations/$id'
      fullPath: '/reclamations/$id'
      preLoaderRoute: typeof ReclamationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/new': {
      id: '/prospects/new'
      path: '/prospects/new'
      fullPath: '/prospects/new'
      preLoaderRoute: typeof ProspectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$prospectId': {
      id: '/prospects/$prospectId'
      path: '/prospects/$prospectId'
      fullPath: '/prospects/$prospectId'
      preLoaderRoute: typeof ProspectsProspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId': {
      id: '/opportunities/$opportunityId'
      path: '/opportunities/$opportunityId'
      fullPath: '/opportunities/$opportunityId'
      preLoaderRoute: typeof OpportunitiesOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$prospectId': {
      id: '/journey/$prospectId'
      path: '/journey/$prospectId'
      fullPath: '/journey/$prospectId'
      preLoaderRoute: typeof JourneyProspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/external-agents': {
      id: '/hr/external-agents'
      path: '/hr/external-agents'
      fullPath: '/hr/external-agents'
      preLoaderRoute: typeof HrExternalAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/commissions': {
      id: '/hr/commissions'
      path: '/hr/commissions'
      fullPath: '/hr/commissions'
      preLoaderRoute: typeof HrCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guichet_/analytics': {
      id: '/guichet_/analytics'
      path: '/guichet/analytics'
      fullPath: '/guichet/analytics'
      preLoaderRoute: typeof GuichetAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$date': {
      id: '/calendar/$date'
      path: '/calendar/$date'
      fullPath: '/calendar/$date'
      preLoaderRoute: typeof CalendarDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects/$prospectId_/edit': {
      id: '/prospects/$prospectId_/edit'
      path: '/prospects/$prospectId/edit'
      fullPath: '/prospects/$prospectId/edit'
      preLoaderRoute: typeof ProspectsProspectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$opportunityId_/edit': {
      id: '/opportunities/$opportunityId_/edit'
      path: '/opportunities/$opportunityId/edit'
      fullPath: '/opportunities/$opportunityId/edit'
      preLoaderRoute: typeof OpportunitiesOpportunityIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId_/edit': {
      id: '/contracts/$contractId_/edit'
      path: '/contracts/$contractId/edit'
      fullPath: '/contracts/$contractId/edit'
      preLoaderRoute: typeof ContractsContractIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UsersRouteChildren {
  UsersUsernameRoute: typeof UsersUsernameRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUsernameRoute: UsersUsernameRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BackofficeRoute: BackofficeRoute,
  ConfigurationRoute: ConfigurationRoute,
  DispatchRoute: DispatchRoute,
  DocumentationRoute: DocumentationRoute,
  GuichetRoute: GuichetRoute,
  LoginRoute: LoginRoute,
  MessagingRoute: MessagingRoute,
  NotificationsRoute: NotificationsRoute,
  ObjectivesRoute: ObjectivesRoute,
  OpportunitesRoute: OpportunitesRoute,
  ProfileRoute: ProfileRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SecurityRoute: SecurityRoute,
  SignupInternalX7k2Route: SignupInternalX7k2Route,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRouteWithChildren,
  CalendarDateRoute: CalendarDateRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  GuichetAnalyticsRoute: GuichetAnalyticsRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrCommissionsRoute: HrCommissionsRoute,
  HrExternalAgentsRoute: HrExternalAgentsRoute,
  HrPayrollRoute: HrPayrollRoute,
  JourneyProspectIdRoute: JourneyProspectIdRoute,
  OpportunitiesOpportunityIdRoute: OpportunitiesOpportunityIdRoute,
  ProspectsProspectIdRoute: ProspectsProspectIdRoute,
  ProspectsNewRoute: ProspectsNewRoute,
  ReclamationsIdRoute: ReclamationsIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ProspectsIndexRoute: ProspectsIndexRoute,
  ReclamationsIndexRoute: ReclamationsIndexRoute,
  ContractsContractIdEditRoute: ContractsContractIdEditRoute,
  OpportunitiesOpportunityIdEditRoute: OpportunitiesOpportunityIdEditRoute,
  ProspectsProspectIdEditRoute: ProspectsProspectIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
